"use client";

import { motion } from "framer-motion";
import { useParams } from "next/navigation";
import Link from "next/link";
import {
  FileText, ChevronLeft, Download, Clock, CheckCircle2, XCircle,
  AlertCircle, MessageSquare, Building2, Calendar, MapPin, DollarSign,
  Shield, Sparkles, FileSignature, X, PenTool
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { ContractStatus } from "@/lib/types";
import { useState, useEffect } from "react";
import { supabase } from "@/lib/supabase";
import { useUser } from "@clerk/nextjs";
import { jsPDF } from "jspdf";
import { SignaturePad } from "@/components/ui/signature-pad";

const STATUS_CONFIG: Record<ContractStatus, { label: string; variant: "default" | "success" | "warning" | "destructive" | "info" | "secondary" | "outline"; icon: React.ElementType; color: string }> = {
  draft: { label: "Draft", variant: "secondary", icon: FileText, color: "text-slate-500" },
  pending: { label: "Pending Company Review", variant: "warning", icon: Clock, color: "text-amber-600 dark:text-amber-400" },
  approved: { label: "Approved & Signed", variant: "success", icon: CheckCircle2, color: "text-emerald-600 dark:text-emerald-400" },
  rejected: { label: "Rejected", variant: "destructive", icon: XCircle, color: "text-red-600 dark:text-red-400" },
  changes_requested: { label: "Changes Requested", variant: "info", icon: AlertCircle, color: "text-blue-600 dark:text-blue-400" },
};

const TIMELINE: { status: ContractStatus; label: string; description: string }[] = [
  { status: "draft", label: "Draft Created", description: "Contract was generated by AI" },
  { status: "pending", label: "Submitted for Review", description: "Sent to company admin dashboard" },
  { status: "approved", label: "Company Decision", description: "Admin approved / rejected / requested changes" },
];

export default function ContractDetailPage() {
  const { id } = useParams();
  const { user } = useUser();
  const [contract, setContract] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [signature, setSignature] = useState<any>(null);
  const [showSignModal, setShowSignModal] = useState(false);

  useEffect(() => {
    async function fetchContractAndSignature() {
      if (!id) return;
      
      // 1. Fetch Contract Details
      const { data, error } = await supabase
        .from("contracts")
        .select("*, companies(company_name)")
        .eq("id", id)
        .single();

      if (!error && data) {
        setContract({
          id: data.id,
          title: data.title,
          status: data.status.toLowerCase().replace(/\s+/g, "_") as ContractStatus,
          createdAt: data.created_at,
          companyName: data.companies?.company_name || data.purpose || "Contract",
          purpose: data.purpose,
          department: data.purpose,
          duration: "1year",
          salary: data.salary || "",
          location: { country: "India", state: "Tamil Nadu", city: "Chennai" },
          content: data.generated_content,
          riskScore: data.risk_score || 0,
          aiSummary: data.ai_summary || "No summary available.",
          adminComment: data.review_comments || "",
        });
      }

      // 2. Fetch Signatures for this contract
      const { data: sigs } = await supabase
        .from("signatures")
        .select("*")
        .eq("contract_id", id);
      
      if (sigs && sigs.length > 0) {
        setSignature(sigs[0]);
      }

      setLoading(false);
    }
    fetchContractAndSignature();
  }, [id]);

  const dataURLtoBlob = (dataurl: string): Blob => {
    const arr = dataurl.split(",");
    const mime = arr[0].match(/:(.*?);/)![1];
    const bstr = atob(arr[1]);
    let n = bstr.length;
    const u8arr = new Uint8Array(n);
    while (n--) {
      u8arr[n] = bstr.charCodeAt(n);
    }
    return new Blob([u8arr], { type: mime });
  };

  const handleSaveSignature = async (dataUrl: string) => {
    if (!id || !user) return;
    
    try {
      const blob = dataURLtoBlob(dataUrl);
      const filePath = `${user.id}/${id}_${Date.now()}.png`;

      // 1. Upload to Supabase Storage
      const { error: uploadError } = await supabase.storage
        .from("digital-signatures")
        .upload(filePath, blob, { contentType: "image/png" });

      if (uploadError) throw uploadError;

      // 2. Get Public URL
      const { data: urlData } = supabase.storage
        .from("digital-signatures")
        .getPublicUrl(filePath);

      const signatureUrl = urlData?.publicUrl || "";

      // 3. Insert record in Database
      const { data: sigData, error: sigError } = await supabase
        .from("signatures")
        .insert({
          contract_id: id,
          signed_by: user.id,
          signature_image: signatureUrl,
          signature_type: "draw",
        })
        .select()
        .single();

      if (sigError) throw sigError;

      setSignature(sigData);
      setShowSignModal(false);
    } catch (err) {
      console.error("Error saving signature:", err);
    }
  };

  const exportToPDF = () => {
    if (!contract) return;
    const doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4"
    });

    const margin = 20;
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const contentWidth = pageWidth - 2 * margin;

    // Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(contract.title.toUpperCase(), margin, 25);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Company: ${contract.companyName}`, margin, 32);
    doc.text(`Date: ${new Date(contract.createdAt).toLocaleDateString()}`, margin, 37);

    doc.setDrawColor(200, 200, 200);
    doc.line(margin, 42, pageWidth - margin, 42);

    // Body
    doc.setFont("courier", "normal");
    doc.setFontSize(9);
    
    const lines = doc.splitTextToSize(contract.content || "No content generated.", contentWidth);
    
    let y = 50;
    const lineHeight = 5;

    for (let i = 0; i < lines.length; i++) {
      if (y > pageHeight - 30) {
        doc.addPage();
        y = 25;
      }
      doc.text(lines[i], margin, y);
      y += lineHeight;
    }

    // Signatures
    if (signature) {
      if (y > pageHeight - 60) {
        doc.addPage();
        y = 30;
      }
      y += 10;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.text("SIGNATURES & VERIFICATION", margin, y);
      
      y += 8;
      doc.setFont("helvetica", "normal");
      doc.text("Digitally Signed by Party:", margin, y);
      doc.text(`Name: ${user?.fullName || "User"}`, margin, y + 5);
      doc.text(`Email: ${user?.primaryEmailAddress?.emailAddress}`, margin, y + 10);
      
      try {
        doc.addImage(signature.signature_image, "PNG", margin + 70, y - 5, 40, 20);
      } catch (e) {
        console.error("Could not render signature image in PDF:", e);
      }
    }

    doc.save(`${contract.title.toLowerCase().replace(/\s+/g, "_")}.pdf`);
  };

  if (loading) {
    return (
      <div className="flex h-[80vh] items-center justify-center">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
      </div>
    );
  }

  if (!contract) {
    return (
      <div className="p-8 text-center">
        <p className="text-muted-foreground">Contract not found.</p>
        <Link href="/contracts" className="mt-4 inline-block">
          <Button variant="outline">Back to Contracts</Button>
        </Link>
      </div>
    );
  }

  const status = STATUS_CONFIG[contract.status as ContractStatus] || STATUS_CONFIG.draft;
  const StatusIcon = status.icon;

  const statusOrder: ContractStatus[] = ["draft", "pending", "approved"];
  const currentStatusIndex = statusOrder.indexOf(
    contract.status === "rejected" || contract.status === "changes_requested"
      ? "approved"
      : contract.status
  );

  return (
    <div className="p-6 lg:p-8 max-w-5xl mx-auto relative">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex items-center gap-4 mb-8"
      >
        <Link href="/contracts">
          <Button variant="outline" size="sm" className="gap-1" id="contract-detail-back">
            <ChevronLeft className="h-4 w-4" /> Back
          </Button>
        </Link>
        <div className="min-w-0 flex-1">
          <h1 className="text-xl font-bold truncate">{contract.title}</h1>
          <p className="text-sm text-muted-foreground mt-0.5">
            {contract.companyName} · Created {new Date(contract.createdAt).toLocaleDateString()}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Badge variant={status.variant}>
            <StatusIcon className="h-3 w-3 mr-1" />
            {status.label}
          </Badge>
          {contract.status === "approved" && (
            <>
              {signature ? (
                <Button size="sm" className="gap-1.5" onClick={exportToPDF} id="contract-download-pdf">
                  <Download className="h-4 w-4" />
                  Download PDF
                </Button>
              ) : (
                <Button size="sm" className="gap-1.5 bg-emerald-600 hover:bg-emerald-700 text-white" onClick={() => setShowSignModal(true)} id="contract-sign-btn">
                  <PenTool className="h-4 w-4" />
                  Sign Contract
                </Button>
              )}
            </>
          )}
        </div>
      </motion.div>

      <div className="grid lg:grid-cols-3 gap-6">
        {/* Left: Main info */}
        <div className="lg:col-span-2 space-y-5">
          {/* Status timeline */}
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="glass-card rounded-2xl p-5"
          >
            <h2 className="text-sm font-semibold mb-4">Contract Status Timeline</h2>
            <div className="relative">
              <div className="absolute left-4 top-5 bottom-5 w-0.5 bg-border" />
              <div className="space-y-4">
                {TIMELINE.map((tl, i) => {
                  const isReached = i <= currentStatusIndex;
                  const isCurrent = i === currentStatusIndex;
                  return (
                    <div key={tl.status} className="flex items-start gap-4">
                      <div className={`relative flex h-8 w-8 shrink-0 items-center justify-center rounded-full border-2 z-10 transition-all ${
                        isReached ? "border-primary bg-primary" : "border-border bg-background"
                      }`}>
                        {isReached ? (
                          <CheckCircle2 className="h-4 w-4 text-primary-foreground" />
                        ) : (
                          <span className="h-2 w-2 rounded-full bg-border" />
                        )}
                      </div>
                      <div className={`pt-1 ${isCurrent ? "" : "opacity-60"}`}>
                        <p className={`text-sm font-medium ${isCurrent ? "text-foreground" : "text-muted-foreground"}`}>
                          {tl.label}
                          {isCurrent && contract.status !== "approved" && (
                            <span className="ml-2 text-xs text-primary font-normal">← Current</span>
                          )}
                        </p>
                        <p className="text-xs text-muted-foreground">{tl.description}</p>
                        {tl.status === "approved" && contract.status === "approved" && (
                          <p className="text-xs text-emerald-600 dark:text-emerald-400 mt-0.5 font-medium">
                            {signature ? "✓ Signed & Finalized" : "⚡ Awaiting Party Signature"}
                          </p>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </motion.div>

          {/* AI Summary */}
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="glass-card rounded-2xl p-5"
          >
            <div className="flex items-center gap-2 mb-3">
              <Sparkles className="h-4 w-4 text-primary" />
              <h2 className="text-sm font-semibold">AI Analysis</h2>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed mb-4">{contract.aiSummary}</p>

            {/* Risk score */}
            <div>
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-medium">Risk Score</span>
                <span className={`text-xs font-bold ${
                  contract.riskScore < 30 ? "text-emerald-600 dark:text-emerald-400" :
                  contract.riskScore < 60 ? "text-amber-600 dark:text-amber-400" : "text-red-600 dark:text-red-400"
                }`}>
                  {contract.riskScore}/100 — {contract.riskScore < 30 ? "Low Risk" : contract.riskScore < 60 ? "Medium Risk" : "High Risk"}
                </span>
              </div>
              <Progress
                value={contract.riskScore}
                indicatorClassName={
                  contract.riskScore < 30 ? "bg-emerald-500" :
                  contract.riskScore < 60 ? "bg-amber-500" : "bg-red-500"
                }
              />
            </div>
          </motion.div>

          {/* Contract Content Document */}
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.25 }}
            className="glass-card rounded-2xl p-6"
          >
            <div className="flex items-center justify-between mb-4 border-b border-border/50 pb-3">
              <div className="flex items-center gap-2">
                <FileText className="h-4 w-4 text-primary" />
                <h2 className="text-sm font-semibold">Contract Document</h2>
              </div>
            </div>
            <div className="p-4 bg-muted/20 border border-border/50 rounded-lg max-h-[60vh] overflow-y-auto font-mono text-xs whitespace-pre-wrap leading-relaxed text-foreground">
              {contract.content || "No content generated yet."}
            </div>
          </motion.div>

          {/* Admin comment */}
          {contract.adminComment && (
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 }}
              className={`glass-card rounded-2xl p-5 border ${
                contract.status === "approved"
                  ? "border-emerald-200 dark:border-emerald-800/40"
                  : contract.status === "rejected"
                  ? "border-red-200 dark:border-red-800/40"
                  : "border-blue-200 dark:border-blue-800/40"
              }`}
            >
              <div className="flex items-center gap-2 mb-2">
                <MessageSquare className="h-4 w-4 text-primary" />
                <h2 className="text-sm font-semibold">Admin Comment</h2>
              </div>
              <p className="text-sm text-muted-foreground">{contract.adminComment}</p>
            </motion.div>
          )}
        </div>

        {/* Right: Details sidebar */}
        <motion.div
          initial={{ opacity: 0, x: 10 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: 0.2 }}
          className="space-y-4"
        >
          {/* Contract Details */}
          <div className="glass-card rounded-2xl p-5">
            <h2 className="text-sm font-semibold mb-4">Contract Details</h2>
            <div className="space-y-3">
              {[
                { icon: Building2, label: "Company", value: contract.companyName },
                { icon: FileSignature, label: "Type", value: contract.purpose.replace(/_/g, " ").replace(/\b\w/g, (l: string) => l.toUpperCase()) },
                { icon: Shield, label: "Department", value: contract.department },
                { icon: Calendar, label: "Duration", value: contract.duration },
                { icon: MapPin, label: "Location", value: [contract.location.city, contract.location.state, contract.location.country].filter(Boolean).join(", ") || "N/A" },
                ...(contract.salary ? [{ icon: DollarSign, label: "Salary", value: contract.salary }] : []),
              ].map((detail) => {
                const Icon = detail.icon;
                return (
                  <div key={detail.label} className="flex items-start gap-3">
                    <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-md bg-muted">
                      <Icon className="h-3.5 w-3.5 text-muted-foreground" />
                    </div>
                    <div>
                      <p className="text-xs text-muted-foreground">{detail.label}</p>
                      <p className="text-xs font-medium capitalize">{detail.value}</p>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Signature Info */}
          {contract.status === "approved" && (
            <div className="glass-card rounded-2xl p-5 border border-border/60">
              <h2 className="text-sm font-semibold mb-3 flex items-center gap-2">
                <FileSignature className="h-4 w-4 text-emerald-600 dark:text-emerald-400" />
                Signoff Status
              </h2>
              {signature ? (
                <div className="space-y-2">
                  <p className="text-xs text-muted-foreground">Signed Digitally by:</p>
                  <p className="text-sm font-semibold text-foreground">{user?.fullName || "User"}</p>
                  <div className="bg-slate-900 border border-border/50 p-2 rounded-lg flex items-center justify-center h-20 overflow-hidden mt-1">
                    <img src={signature.signature_image} alt="Signature" className="max-h-full max-w-full object-contain filter invert dark:invert-0" />
                  </div>
                  <p className="text-[10px] text-muted-foreground mt-1">Signed on {new Date(signature.signed_at).toLocaleString()}</p>
                  <p className="text-xs text-emerald-600 dark:text-emerald-400 font-medium pt-1">
                    ✓ Verified Contract Signature
                  </p>
                </div>
              ) : (
                <div>
                  <p className="text-xs text-muted-foreground mb-3 leading-relaxed">
                    This contract is approved by the admin and awaits your formal digital signature to be finalized.
                  </p>
                  <Button size="sm" className="w-full bg-emerald-600 hover:bg-emerald-700 text-white gap-1.5" onClick={() => setShowSignModal(true)}>
                    <PenTool className="h-3.5 w-3.5" /> Sign Contract Now
                  </Button>
                </div>
              )}
            </div>
          )}
        </motion.div>
      </div>

      {/* Signature Modal */}
      {showSignModal && (
        <div className="fixed inset-0 bg-background/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <motion.div
            initial={{ scale: 0.95, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            className="bg-card border border-border/80 rounded-2xl shadow-xl w-full max-w-md p-6 relative"
          >
            <button
              onClick={() => setShowSignModal(false)}
              className="absolute top-4 right-4 text-muted-foreground hover:text-foreground"
            >
              <X className="h-4 w-4" />
            </button>
            <h3 className="text-lg font-bold mb-1">Digitally Sign Contract</h3>
            <p className="text-xs text-muted-foreground mb-4">
              Draw your signature in the panel below. By clicking confirm, you agree to embed this signature into the official contract document.
            </p>
            <SignaturePad onSave={handleSaveSignature} />
          </motion.div>
        </div>
      )}
    </div>
  );
}
