"use client";

import { motion } from "framer-motion";
import { useParams } from "next/navigation";
import Link from "next/link";
import {
  FileText, ChevronLeft, Download, Clock, CheckCircle2, XCircle,
  AlertCircle, MessageSquare, Building2, Calendar, MapPin, DollarSign,
  Shield, Sparkles, FileSignature,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { CONTRACTS } from "@/lib/mock-data";
import { ContractStatus } from "@/lib/types";

const STATUS_CONFIG: Record<ContractStatus, { label: string; variant: "default" | "success" | "warning" | "destructive" | "info" | "secondary" | "outline"; icon: React.ElementType; color: string }> = {
  draft: { label: "Draft", variant: "secondary", icon: FileText, color: "text-slate-500" },
  pending: { label: "Pending Company Review", variant: "warning", icon: Clock, color: "text-amber-600 dark:text-amber-400" },
  approved: { label: "Approved & Signed", variant: "success", icon: CheckCircle2, color: "text-emerald-600 dark:text-emerald-400" },
  rejected: { label: "Rejected", variant: "destructive", icon: XCircle, color: "text-red-600 dark:text-red-400" },
  changes_requested: { label: "Changes Requested", variant: "info", icon: AlertCircle, color: "text-blue-600 dark:text-blue-400" },
};

const TIMELINE: { status: ContractStatus; label: string; description: string }[] = [
  { status: "draft", label: "Draft Created", description: "Contract was generated by AI" },
  { status: "pending", label: "Submitted for Review", description: "Sent to company admin dashboard" },
  { status: "approved", label: "Company Decision", description: "Admin approved / rejected / requested changes" },
];

export default function ContractDetailPage() {
  const { id } = useParams();
  const contract = CONTRACTS.find((c) => c.id === id);

  if (!contract) {
    return (
      <div className="p-8 text-center">
        <p className="text-muted-foreground">Contract not found.</p>
        <Link href="/contracts" className="mt-4 inline-block">
          <Button variant="outline">Back to Contracts</Button>
        </Link>
      </div>
    );
  }

  const status = STATUS_CONFIG[contract.status];
  const StatusIcon = status.icon;

  const statusOrder: ContractStatus[] = ["draft", "pending", "approved"];
  const currentStatusIndex = statusOrder.indexOf(
    contract.status === "rejected" || contract.status === "changes_requested"
      ? "approved"
      : contract.status
  );

  return (
    <div className="p-6 lg:p-8 max-w-5xl mx-auto">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex items-center gap-4 mb-8"
      >
        <Link href="/contracts">
          <Button variant="outline" size="sm" className="gap-1" id="contract-detail-back">
            <ChevronLeft className="h-4 w-4" /> Back
          </Button>
        </Link>
        <div className="min-w-0 flex-1">
          <h1 className="text-xl font-bold truncate">{contract.title}</h1>
          <p className="text-sm text-muted-foreground mt-0.5">
            {contract.companyName} · Created {new Date(contract.createdAt).toLocaleDateString()}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Badge variant={status.variant}>
            <StatusIcon className="h-3 w-3 mr-1" />
            {status.label}
          </Badge>
          {contract.status === "approved" && (
            <Button size="sm" className="gap-1.5" id="contract-download-approved">
              <Download className="h-4 w-4" />
              Download
            </Button>
          )}
        </div>
      </motion.div>

      <div className="grid lg:grid-cols-3 gap-6">
        {/* Left: Main info */}
        <div className="lg:col-span-2 space-y-5">
          {/* Status timeline */}
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="glass-card rounded-2xl p-5"
          >
            <h2 className="text-sm font-semibold mb-4">Contract Status Timeline</h2>
            <div className="relative">
              <div className="absolute left-4 top-5 bottom-5 w-0.5 bg-border" />
              <div className="space-y-4">
                {TIMELINE.map((tl, i) => {
                  const isReached = i <= currentStatusIndex;
                  const isCurrent = i === currentStatusIndex;
                  return (
                    <div key={tl.status} className="flex items-start gap-4">
                      <div className={`relative flex h-8 w-8 shrink-0 items-center justify-center rounded-full border-2 z-10 transition-all ${
                        isReached ? "border-primary bg-primary" : "border-border bg-background"
                      }`}>
                        {isReached ? (
                          <CheckCircle2 className="h-4 w-4 text-primary-foreground" />
                        ) : (
                          <span className="h-2 w-2 rounded-full bg-border" />
                        )}
                      </div>
                      <div className={`pt-1 ${isCurrent ? "" : "opacity-60"}`}>
                        <p className={`text-sm font-medium ${isCurrent ? "text-foreground" : "text-muted-foreground"}`}>
                          {tl.label}
                          {isCurrent && contract.status !== "approved" && (
                            <span className="ml-2 text-xs text-primary font-normal">← Current</span>
                          )}
                        </p>
                        <p className="text-xs text-muted-foreground">{tl.description}</p>
                        {tl.status === "approved" && contract.status === "approved" && contract.approvedAt && (
                          <p className="text-xs text-emerald-600 dark:text-emerald-400 mt-0.5">
                            ✓ Approved on {new Date(contract.approvedAt).toLocaleDateString()}
                          </p>
                        )}
                        {tl.status === "approved" && contract.status === "rejected" && (
                          <p className="text-xs text-red-600 dark:text-red-400 mt-0.5">✗ Rejected</p>
                        )}
                        {tl.status === "approved" && contract.status === "changes_requested" && (
                          <p className="text-xs text-blue-600 dark:text-blue-400 mt-0.5">⚡ Changes Requested</p>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </motion.div>

          {/* AI Summary */}
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="glass-card rounded-2xl p-5"
          >
            <div className="flex items-center gap-2 mb-3">
              <Sparkles className="h-4 w-4 text-primary" />
              <h2 className="text-sm font-semibold">AI Analysis</h2>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed mb-4">{contract.aiSummary}</p>

            {/* Risk score */}
            <div>
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-medium">Risk Score</span>
                <span className={`text-xs font-bold ${
                  contract.riskScore < 30 ? "text-emerald-600 dark:text-emerald-400" :
                  contract.riskScore < 60 ? "text-amber-600 dark:text-amber-400" : "text-red-600 dark:text-red-400"
                }`}>
                  {contract.riskScore}/100 — {contract.riskScore < 30 ? "Low Risk" : contract.riskScore < 60 ? "Medium Risk" : "High Risk"}
                </span>
              </div>
              <Progress
                value={contract.riskScore}
                indicatorClassName={
                  contract.riskScore < 30 ? "bg-emerald-500" :
                  contract.riskScore < 60 ? "bg-amber-500" : "bg-red-500"
                }
              />
            </div>
          </motion.div>

          {/* Admin comment */}
          {contract.adminComment && (
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 }}
              className={`glass-card rounded-2xl p-5 border ${
                contract.status === "approved"
                  ? "border-emerald-200 dark:border-emerald-800/40"
                  : contract.status === "rejected"
                  ? "border-red-200 dark:border-red-800/40"
                  : "border-blue-200 dark:border-blue-800/40"
              }`}
            >
              <div className="flex items-center gap-2 mb-2">
                <MessageSquare className="h-4 w-4 text-primary" />
                <h2 className="text-sm font-semibold">Admin Comment</h2>
              </div>
              <p className="text-sm text-muted-foreground">{contract.adminComment}</p>
              {contract.approvedAt && (
                <p className="text-xs text-muted-foreground mt-2">
                  — {contract.signatoryName}, {contract.signatoryTitle} · {new Date(contract.approvedAt).toLocaleDateString()}
                </p>
              )}
            </motion.div>
          )}
        </div>

        {/* Right: Details sidebar */}
        <motion.div
          initial={{ opacity: 0, x: 10 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: 0.2 }}
          className="space-y-4"
        >
          {/* Contract Details */}
          <div className="glass-card rounded-2xl p-5">
            <h2 className="text-sm font-semibold mb-4">Contract Details</h2>
            <div className="space-y-3">
              {[
                { icon: Building2, label: "Company", value: contract.companyName },
                { icon: FileSignature, label: "Type", value: contract.purpose.replace(/_/g, " ").replace(/\b\w/g, (l) => l.toUpperCase()) },
                { icon: Shield, label: "Department", value: contract.department },
                { icon: Calendar, label: "Duration", value: contract.duration },
                { icon: MapPin, label: "Location", value: [contract.location.city, contract.location.state, contract.location.country].filter(Boolean).join(", ") || "N/A" },
                ...(contract.salary ? [{ icon: DollarSign, label: "Salary", value: contract.salary }] : []),
              ].map((detail) => {
                const Icon = detail.icon;
                return (
                  <div key={detail.label} className="flex items-start gap-3">
                    <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-md bg-muted">
                      <Icon className="h-3.5 w-3.5 text-muted-foreground" />
                    </div>
                    <div>
                      <p className="text-xs text-muted-foreground">{detail.label}</p>
                      <p className="text-xs font-medium capitalize">{detail.value}</p>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Signature Info */}
          {contract.status === "approved" && contract.signatoryName && (
            <div className="glass-card rounded-2xl p-5 border border-emerald-200 dark:border-emerald-800/40">
              <h2 className="text-sm font-semibold mb-3 flex items-center gap-2">
                <FileSignature className="h-4 w-4 text-emerald-600 dark:text-emerald-400" />
                Official Signature
              </h2>
              <p className="text-sm font-medium">{contract.signatoryName}</p>
              <p className="text-xs text-muted-foreground">{contract.signatoryTitle}</p>
              <p className="text-xs text-muted-foreground mt-1">{contract.companyName}</p>
              <div className="mt-3 h-px bg-border" />
              <p className="text-xs text-emerald-600 dark:text-emerald-400 mt-2 font-medium">
                ✓ Digitally signed & verified
              </p>
            </div>
          )}
        </motion.div>
      </div>
    </div>
  );
}
